# == Variables ==
Variables:
  teams-notification:
    enabled: true
    permissions: "Chat.Write"
    # technical user that sends ivy-notifications
    username: ""
    # secret of the technical user
    # [password]
    userpass: "${encrypt:somePass}"
