RestClients:
  team-notification:
    UUID: fb0c277e-35a3-481f-8f79-edca67ce1145
    Url: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/graphMock
    Icon: res:/webContent/icons/microsoft.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - ch.ivyteam.ivy.rest.client.security.CsrfHeaderFeature
    Properties:
      jersey.client.connectorProvider: org.glassfish.jersey.client.HttpUrlConnectorProvider
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
